name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Install scdoc
      run: |
        git clone https://git.sr.ht/~sircmpwn/scdoc
        cd scdoc
        make
        sudo make install

    - name: Build
      run: make

    # - name: Test
    #   run: make check
